//! `NSPasteboard` access, the `changeCount` poll, and save/restore (§8, §12).
//!
//! **macOS has no clipboard change notification.** There is no
//! `NSPasteboardDidChangeNotification`; the only way to learn that the
//! pasteboard moved is to compare `changeCount` against the last value you saw.
//! Everything in this module is built around that single fact:
//!
//! * the synthetic-`⌘C` selection fallback polls `changeCount` until it ticks
//!   or the §8 deadline expires (250 ms including this fallback);
//! * save/restore is **a race, not an assignment** (§12) — aibo restores only
//!   when `changeCount` still equals the value its own write produced;
//! * concealed items are never read into memory and never restored;
//! * promised/deferred formats cannot be restored faithfully, so they are
//!   detected and the restore is declined rather than silently downgrading rich
//!   content to plain text.

use std::path::PathBuf;
use std::time::{Duration, Instant};

use aibo_core::types::{ClipboardItem, ClipboardKind};
use objc2::rc::Retained;
use objc2_app_kit::{NSPasteboard, NSPasteboardType};
use objc2_foundation::{NSArray, NSData, NSString, NSURL};

/// `org.nspasteboard.ConcealedType` — a password manager saying "do not record
/// this". A community convention, **not** an Apple API (§20).
pub const NS_PASTEBOARD_CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// `org.nspasteboard.TransientType` — usable now, never persisted.
pub const NS_PASTEBOARD_TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
/// `org.nspasteboard.AutoGeneratedType` — written by a tool, not by the user.
pub const NS_PASTEBOARD_AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

// The `NSPasteboardType*` constants are `extern "C"` statics, so every mention
// needs an `unsafe` block. Wrapping them once keeps the rest of this module
// free of `unsafe` noise and gives each one a single SAFETY justification:
// they are framework-owned strings valid for the whole process lifetime.
#[allow(unsafe_code)]
mod uti {
    use objc2_app_kit::{
        NSPasteboardType, NSPasteboardTypeFileURL, NSPasteboardTypePNG, NSPasteboardTypeRTF,
        NSPasteboardTypeString, NSPasteboardTypeTIFF,
    };

    /// `public.utf8-plain-text`.
    pub(super) fn string() -> &'static NSPasteboardType {
        // SAFETY: framework constant, valid for the process lifetime.
        unsafe { NSPasteboardTypeString }
    }
    /// `public.file-url`.
    pub(super) fn file_url() -> &'static NSPasteboardType {
        // SAFETY: as above.
        unsafe { NSPasteboardTypeFileURL }
    }
    /// `public.tiff`.
    pub(super) fn tiff() -> &'static NSPasteboardType {
        // SAFETY: as above.
        unsafe { NSPasteboardTypeTIFF }
    }
    /// `public.png`.
    pub(super) fn png() -> &'static NSPasteboardType {
        // SAFETY: as above.
        unsafe { NSPasteboardTypePNG }
    }
    /// `public.rtf` — not read yet, but §5's Transform surface must eventually
    /// preserve rich text rather than flattening it.
    #[allow(dead_code)]
    pub(super) fn rtf() -> &'static NSPasteboardType {
        // SAFETY: as above.
        unsafe { NSPasteboardTypeRTF }
    }
}

/// How often the `changeCount` poll wakes up.
///
/// 5 ms is a compromise: the synthetic-`⌘C` round trip is "tens of
/// milliseconds, app-dependent, and sometimes never" (§8), and a tighter loop
/// only burns CPU inside a 250 ms budget.
const POLL_INTERVAL: Duration = Duration::from_millis(5);

/// The general pasteboard.
fn pasteboard() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

/// Current `changeCount`. The only change signal macOS offers.
pub(crate) fn change_count() -> i64 {
    pasteboard().changeCount() as i64
}

fn advertised_types(pb: &NSPasteboard) -> Vec<String> {
    pb.types()
        .map(|types| types.iter().map(|t| t.to_string()).collect())
        .unwrap_or_default()
}

fn has_type(types: &[String], wanted: &NSPasteboardType) -> bool {
    let wanted = wanted.to_string();
    types.contains(&wanted)
}

fn kind_for(types: &[String]) -> ClipboardKind {
    if types.is_empty() {
        ClipboardKind::Empty
    } else if has_type(types, uti::file_url()) {
        ClipboardKind::Files
    } else if has_type(types, uti::string()) {
        ClipboardKind::Text
    } else if has_type(types, uti::tiff()) || has_type(types, uti::png()) {
        ClipboardKind::ImageRef
    } else {
        ClipboardKind::Unsupported
    }
}

/// Read the clipboard, honouring the §12 hygiene markers.
///
/// `source_app` is the bundle identifier the caller believes owns the current
/// item; it is used only for the denylist, because macOS does not report the
/// pasteboard's owner.
///
/// SPIKE: S4 — the marker conventions and the promised-format detection below
/// need validating against real password managers and against apps that supply
/// data lazily.
pub(crate) fn read(source_app: Option<&str>) -> ClipboardItem {
    let pb = pasteboard();
    let sequence = pb.changeCount() as u64;
    let types = advertised_types(&pb);

    let denylisted = source_app.is_some_and(super::apps::is_clipboard_denylisted);
    let concealed = denylisted || types.iter().any(|t| t == NS_PASTEBOARD_CONCEALED_TYPE);
    let transient = types.iter().any(|t| t == NS_PASTEBOARD_TRANSIENT_TYPE);
    let kind = kind_for(&types);

    // §12: "Concealed items are not recorded at all" — the payload is never
    // pulled into aibo's address space, not merely dropped later.
    let text = if concealed || kind != ClipboardKind::Text {
        None
    } else {
        // SAFETY: `NSPasteboardTypeString` is a framework constant valid for the
        // process lifetime.
        pb.stringForType(uti::string()).map(|s| s.to_string())
    };

    let files = if concealed || kind != ClipboardKind::Files {
        Vec::new()
    } else {
        read_file_urls(&pb)
    };

    ClipboardItem {
        kind,
        text,
        files,
        concealed,
        transient,
        source_app: source_app.map(str::to_owned),
        sequence,
        restorable: !concealed && is_restorable(&pb, &types),
    }
}

fn read_file_urls(pb: &NSPasteboard) -> Vec<PathBuf> {
    let Some(items) = pb.pasteboardItems() else {
        return Vec::new();
    };
    items
        .iter()
        .filter_map(|item| {
            // SAFETY: framework constant.
            let s = item.stringForType(uti::file_url())?;
            let url = NSURL::URLWithString(&s)?;
            url.path().map(|p| PathBuf::from(p.to_string()))
        })
        .collect()
}

/// Can the current contents be put back byte-for-byte?
///
/// Returns `false` for multi-item pasteboards (restoring them needs
/// `NSPasteboardItem` round-tripping that cannot preserve promises either) and
/// for any advertised type whose data is not actually available — the
/// signature of a promised/deferred format (§12).
fn is_restorable(pb: &NSPasteboard, types: &[String]) -> bool {
    if types.is_empty() {
        return true;
    }
    if pb.pasteboardItems().is_some_and(|items| items.len() > 1) {
        return false;
    }
    types.iter().all(|t| {
        if t.starts_with("org.nspasteboard.") {
            // Marker types legitimately carry no data.
            return true;
        }
        let ns = NSString::from_str(t);
        pb.dataForType(&ns).is_some()
    })
}

/// Everything needed to put the clipboard back exactly as it was.
pub(crate) struct PasteboardSnapshot {
    /// `changeCount` at the time of the snapshot.
    pub change_count: i64,
    /// `(uti, bytes)` for every advertised type that had data.
    entries: Vec<(String, Vec<u8>)>,
    /// False when the contents could not be captured faithfully; restoring
    /// anyway would destroy rich content (§12).
    pub restorable: bool,
    /// True when the previous contents were concealed. **Never restore these** —
    /// aibo does not hold a copy in the first place.
    pub concealed: bool,
}

/// Snapshot the clipboard before clobbering it.
pub(crate) fn snapshot() -> PasteboardSnapshot {
    let pb = pasteboard();
    let change_count = pb.changeCount() as i64;
    let types = advertised_types(&pb);
    let concealed = types.iter().any(|t| t == NS_PASTEBOARD_CONCEALED_TYPE);
    let restorable = !concealed && is_restorable(&pb, &types);

    let entries = if restorable {
        types
            .iter()
            .filter_map(|t| {
                let ns = NSString::from_str(t);
                pb.dataForType(&ns).map(|d| (t.clone(), d.to_vec()))
            })
            .collect()
    } else {
        Vec::new()
    };

    PasteboardSnapshot {
        change_count,
        entries,
        restorable,
        concealed,
    }
}

/// Why a restore did not happen. Never an error — all three outcomes are
/// correct behaviour under §12.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RestoreOutcome {
    /// The previous contents are back.
    Restored,
    /// Something other than aibo wrote to the clipboard in the meantime;
    /// restoring would destroy what the user just copied.
    SkippedRaced,
    /// The previous contents were concealed, or contained a promised format.
    SkippedUnrestorable,
}

/// Put the snapshot back, but only if aibo is still the last writer.
///
/// `expected` is the `changeCount` aibo's own write produced. If the live value
/// differs, the user copied something between the paste and now — §12 is
/// explicit that the correct action is to leave it alone.
pub(crate) fn restore(snapshot: &PasteboardSnapshot, expected: i64) -> RestoreOutcome {
    if snapshot.concealed || !snapshot.restorable {
        return RestoreOutcome::SkippedUnrestorable;
    }
    let pb = pasteboard();
    if pb.changeCount() as i64 != expected {
        return RestoreOutcome::SkippedRaced;
    }
    if snapshot.entries.is_empty() {
        pb.clearContents();
        return RestoreOutcome::Restored;
    }

    let type_objects: Vec<Retained<NSString>> = snapshot
        .entries
        .iter()
        .map(|(t, _)| NSString::from_str(t))
        .collect();
    let type_array = NSArray::from_retained_slice(&type_objects);
    // SAFETY: `declareTypes:owner:` with a nil owner is the standard
    // no-lazy-provider form; the array outlives the call.
    #[allow(unsafe_code)]
    unsafe {
        pb.declareTypes_owner(&type_array, None)
    };
    for (uti, bytes) in &snapshot.entries {
        let ns_type = NSString::from_str(uti);
        let data = NSData::with_bytes(bytes);
        pb.setData_forType(Some(&data), &ns_type);
    }
    RestoreOutcome::Restored
}

/// Write `text` for aibo's own paste, tagged so clipboard managers skip it.
///
/// §20's trap: the `org.nspasteboard.*` markers **must be declared in the same
/// `declareTypes:owner:` transaction** as the payload. Declaring them
/// separately bumps `changeCount` twice and managers capture the first,
/// unmarked item.
///
/// Returns the `changeCount` produced by this write, which is the token
/// [`restore`] checks against.
pub(crate) fn write_transient_text(text: &str) -> i64 {
    let pb = pasteboard();
    // SAFETY: framework constant.
    let string_type = uti::string();
    let transient = NSString::from_str(NS_PASTEBOARD_TRANSIENT_TYPE);
    let auto_generated = NSString::from_str(NS_PASTEBOARD_AUTO_GENERATED_TYPE);
    let type_array = NSArray::from_slice(&[string_type, &transient, &auto_generated]);
    // SAFETY: one transaction, nil owner; see the doc comment above.
    #[allow(unsafe_code)]
    let count = unsafe { pb.declareTypes_owner(&type_array, None) };
    pb.setString_forType(&NSString::from_str(text), string_type);
    // The marker types carry no payload; an empty NSData keeps them present.
    let empty = NSData::with_bytes(&[]);
    for marker in [
        NS_PASTEBOARD_TRANSIENT_TYPE,
        NS_PASTEBOARD_AUTO_GENERATED_TYPE,
    ] {
        pb.setData_forType(Some(&empty), &NSString::from_str(marker));
    }
    count as i64
}

/// Block until `changeCount` moves past `baseline`, or the deadline expires.
///
/// This is the synthetic-`⌘C` half of §8's 250 ms budget. It runs on the
/// dedicated platform thread, never on the UI thread, and it returns `None`
/// rather than an error because "the app swallowed the shortcut" is an
/// expected, silent outcome that the panel must tolerate.
pub(crate) fn wait_for_change(baseline: i64, deadline: Duration) -> Option<i64> {
    let start = Instant::now();
    loop {
        let now = change_count();
        if now != baseline {
            return Some(now);
        }
        if start.elapsed() >= deadline {
            return None;
        }
        std::thread::sleep(POLL_INTERVAL);
    }
}

/// Read the plain-text payload without any hygiene processing.
///
/// Only used immediately after [`wait_for_change`] confirmed aibo's own
/// synthetic copy landed.
pub(crate) fn read_string() -> Option<String> {
    // SAFETY: framework constant.
    pasteboard()
        .stringForType(uti::string())
        .map(|s| s.to_string())
}
